[package]
name = "quarry-registry"
version = "1.4.0"
description = "Registry of all quarries associated with a rewarder."
edition = "2018"
homepage = "https://quarry.so"
repository = "https://github.com/QuarryProtocol/quarry"
authors = ["Quarry Protocol <team@quarry.so>"]
license = "AGPL-3.0"
keywords = ["solana"]

[lib]
crate-type = ["cdylib", "lib"]
name = "quarry_registry"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.13.2"
quarry-mine = { version = "1.1.0", path = "../quarry-mine", features = ["cpi"] }
solana-program = "1.7.8"
vipers = "0.1.1"
