[package]
name = "quarry-mint-wrapper"
version = "0.2.0"
description = "Created with Anchor"
edition = "2018"
homepage = "https://quarry.so"
repository = "https://github.com/QuarryProtocol/quarry"
authors = ["Larry Jarry <larry@quarry.so"]
license = "AGPL-3.0"

[lib]
crate-type = ["cdylib", "lib"]
name = "quarry_mint_wrapper"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.13.2"
anchor-spl = "0.13.2"
vipers = "0.1.1"
solana-program = "1.7.8"
