name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always
  SOLANA_VERSION: "1.7.10"
  RUST_TOOLCHAIN: nightly-2021-08-14
  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build and release the programs
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
          install_options: "--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve"
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Setup Cachix
        uses: cachix/cachix-action@v10
        with:
          name: quarry
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: 14.x
      - name: Cache Node modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn dependencies
        run: yarn install
      - name: Parse IDLs
        run: nix shell .#ci --command yarn idl:generate
      - run: yarn build
      - name: Publish
        run: yarn publish
